name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # or master, if your main branch is named that
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-book-theme nbsphinx ipykernel matplotlib numpy pandas

    - name: Build Docs
      working-directory: ./docs
      run: make html

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html