name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main  

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # match your dev version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo  # or your theme + extensions

      - name: Build Docs
        working-directory: docs
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages